py_test(
    name = "test_main",
    srcs = ["test_main.py"],
    deps = ["//:helper_lib"],
)

#cc_test(
#    name = "test_math_utils",
#    srcs = ["test_math_utils.cc"],
#    deps = ["//cpp_lib:math_utils"],
#)
